In [1]:
#pip install numpy


Note: you may need to restart the kernel to use updated packages.Collecting numpy
     ---------------------------------------- 0.0/60.9 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.9 kB ? eta -:--:--
     ------------ ------------------------- 20.5/60.9 kB 131.3 kB/s eta 0:00:01
     ------------------------- ------------ 41.0/60.9 kB 217.9 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/60.9 kB 262.6 kB/s eta 0:00:01
     -------------------------------------- 60.9/60.9 kB 269.5 kB/s eta 0:00:00
   ---------------------------------------- 0.0/16.2 MB ? eta -:--:--
   ---------------------------------------- 0.1/16.2 MB 2.0 MB/s eta 0:00:09
   ---------------------------------------- 0.2/16.2 MB 2.1 MB/s eta 0:00:08
    --------------------------------------- 0.3/16.2 MB 2.5 MB/s eta 0:00:07
   - -------------------------------------- 0.5/16.2 MB 2.9 MB/s eta 0:00:06
   - -------------------------------------- 0.6/16.2 MB 2.8 MB/s eta 0:00:0

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 24.0 -> 24.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
import numpy as np

In [3]:
l = [1,2,3]
ar = np.array(l)
print(l)
print(ar)
print(type(l))
print(type(ar))


[1, 2, 3]
[1 2 3]
<class 'list'>
<class 'numpy.ndarray'>


In [4]:
ar = np.arange(10)
print(ar)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
import numpy as np

In [4]:
#creating two dimensional arrays
n1 = np.array([[1,2,3],[4,5,6]])
print(n1)

[[1 2 3]
 [4 5 6]]


In [5]:
#array filled with zeros
n3 = np.zeros([2,4])
print(n3)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
#array filled with ones
n4 = np.ones([2,4])
print(n4)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
#two array with 3 by 3 matrix
n2 = np.ones([2,3,3])
print(n2)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [8]:
#empty array with random values
n5 = np.empty([2,3])
print(n5)

[[-1.42238135e-311 -6.71836014e-257  1.42241907e-311]
 [ 1.42241907e-311  5.43472210e-323  3.95252517e-323]]


In [9]:
n6 = np.arange(10)
n6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
#range function with the interval of five
n7 =  np.arange(-5,11,5)
n7

array([-5,  0,  5, 10])

In [15]:
#linearly equal space entry
n8 = np.linspace(0,20, num=5, dtype = np.int32)
n8

array([ 0,  5, 10, 15, 20], dtype=int32)

In [17]:
#filling the matrix with a value
n10 = np.full([2,4], 5)
n10

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

Accessing row and coloumn

In [19]:
n1

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
print(n1[1,2])

6


In [21]:
print(n1[0,:])

[1 2 3]


In [22]:
print(n1[:,1])

[2 5]


Changing values in array

In [23]:
n2

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [25]:
n2[1,2,1] = 27
n2

array([[[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1., 27.,  1.]]])

In [30]:
#Sorting 1d array
n11 = np.array([8,7,2,1,6,9])
np.sort(n11)

array([1, 2, 6, 7, 8, 9])